// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxMz4MnFfhL7v5cUWhXbch5IZevvckVaw',
    appId: '1:64894053069:web:0dd53fc5bf1a3957e11784',
    messagingSenderId: '64894053069',
    projectId: 'cricket-admin-c0c62',
    authDomain: 'cricket-admin-c0c62.firebaseapp.com',
    storageBucket: 'cricket-admin-c0c62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UOKSc1YZqvk_u48hGvAT5Q5trDv19Y4',
    appId: '1:64894053069:android:cb7fae04c859c17ce11784',
    messagingSenderId: '64894053069',
    projectId: 'cricket-admin-c0c62',
    storageBucket: 'cricket-admin-c0c62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwDKgczr8CSMZ8sJtlXkOyZNRO16twolY',
    appId: '1:64894053069:ios:8ba38c3d71d0b6abe11784',
    messagingSenderId: '64894053069',
    projectId: 'cricket-admin-c0c62',
    storageBucket: 'cricket-admin-c0c62.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwDKgczr8CSMZ8sJtlXkOyZNRO16twolY',
    appId: '1:64894053069:ios:8ba38c3d71d0b6abe11784',
    messagingSenderId: '64894053069',
    projectId: 'cricket-admin-c0c62',
    storageBucket: 'cricket-admin-c0c62.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxMz4MnFfhL7v5cUWhXbch5IZevvckVaw',
    appId: '1:64894053069:web:0dd53fc5bf1a3957e11784',
    messagingSenderId: '64894053069',
    projectId: 'cricket-admin-c0c62',
    authDomain: 'cricket-admin-c0c62.firebaseapp.com',
    storageBucket: 'cricket-admin-c0c62.appspot.com',
  );
}
